### PR TITLE
Apple's Page Clone Project - Microverse - Code Review

### PR DESCRIPTION
**Pull request by kevcap**
This page have all the features required and extras:
- Hover effect on navbar;
- focus and transition effect on search input;
- magnifier switch its color when search input gets focus;
- HTML & CSS validation;

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Kevinalvesdev      
#### Great Job so far, but there are a few more things required. 
## Required Changes:
#### General 
 - [x] Kindly note that commits should be descriptive  https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
- [x] Files not related to the project should not be committed, lets remove `package-lock.json` as this not required in this project.
- [x] The page has a horizontal scrolling ,lets fix that. 

### Make changes and submit another code review request.
*Happy coding*

**Comment by kevcap** [comment]
Dear TSE @kobiyoyo 
As you can see, on my screen, there's no horizontal scroll bar, just when the window is not maximized, check it [here](https://imgur.com/a/EyAoUgQ). next time post a full screenshot of your screen, not just the page.

**Comment by Kevinalvesdev** [comment]
[Here's your screenshot](blob:https://imgur.com/b81c0dbf-5a1f-47a5-8b8d-d991c4ce7d2f), clearly wasn't maximized.

**Comment by kevcap** [comment]
Here's your [screenshot,](https://imgur.com/a/qurxi4h) clearly wasn't maximized.

**Comment by kevcap** [comment]
[this one is from my friend's screen](https://imgur.com/a/TlCyet8)

**Comment by kevcap** [comment]
[here's another one](https://imgur.com/a/kSxA0Uu) and I'll take care on next commits.

**Comment by davidmrtz-dev** [comment]
### **Status: Approved.** ✅ 
### **Congragulations!** 🎉 
****
### Hi Team. 😄 
****
Great Job 💯  @Kevinalvesdev , You correctly implemented all the specifications.
You can move onto the next project. 🎊 
Happy coding! 😄 💻  
****
**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Pull request merged**
